// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title UniquenessVerifier
/// @notice A minimal placeholder ZK-verifier for the proof-of-uniqueness
///         scheme.  In production this would be generated by circom + snarkjs
///         from a circuit that proves:
///           "I know a secret S such that hash(S) == C (a commitment)
///            AND I have not previously used nullifier N."
///
///         The present contract acts as a simple on-chain verifier stub
///         so the rest of the system can be tested end-to-end.  Replace
///         the `verifyProof` logic with a real pairing-based verifier.
contract UniquenessVerifier {
    /// @notice Circuit verifying key — for production use a structured
    ///         reference string or stored verifying key.
    bytes32 public immutable verifyingKeyHash;

    /// @param _verifyingKeyHash  Keccak-256 hash of the verifying key.
    constructor(bytes32 _verifyingKeyHash) {
        verifyingKeyHash = _verifyingKeyHash;
    }

    /// @notice Stub verifier — accepts any non-empty proof for non-empty publicInputs.
    /// @dev **DO NOT USE THIS IN PRODUCTION** — it has zero soundness.
    function verifyProof(
        bytes calldata /*proof*/,
        uint256[] calldata publicInputs
    ) external pure returns (bool) {
        // Stub: accept any well-formed call so the pool can be exercised.
        // Replace with real ec-pairing verification.
        return publicInputs.length > 0;
    }

    /// @notice Return the expected length of a valid proof (for frontend
    ///         encoding).  Placeholder — real circuits use e.g. 8 * 32 bytes.
    function expectedProofLength() external pure returns (uint256) {
        return 256; // dummy value
    }
}
